config/routes.rb
Laboralmedical2013::Application.routes.draw do

  devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  match '/servicios' => 'categorias#servicios', via: :get

  match '/consultorias' => 'categorias#consultorias', via: :get

  scope '/blog' do
    resources :noticias
  end

  resources :categorias do
    resources :servicios
  end

  resources :contactos

  resources :alianzas

  resources :servicios

  scope '/staff' do
    resources :miembros
  end

  resources :clientes

  resources :banners

  root to: 'inicio#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/alianza.rb
class Alianza < ActiveRecord::Base
  attr_accessible :nombre, :logo, :posicion

  default_scope order('posicion ASC')

  mount_uploader :logo, LogoUploader
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  attr_accessible :encabezado, :imagen, :link

  mount_uploader :imagen, SlideUploader
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  attr_accessible :nombre

  has_many :servicios
  TIPOS = ['Servicios','Consultorias']
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :link, :logo

  mount_uploader :logo, IconoUploader

  def self.random
    self.all.sample(4)
  end

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  attr_accessible :email, :mensaje, :nombre, :telefono
end

app/models/miembro.rb
class Miembro < ActiveRecord::Base
  attr_accessible :descripcion, :nombre, :puesto, :foto, :apellido, :posicion

  default_scope order('posicion ASC')

  extend FriendlyId
  friendly_id :nombre, use: :slugged

  mount_uploader :foto, FotoUploader
end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
  attr_accessible :contenido, :imagen, :subtitulo, :titulo

extend FriendlyId
  friendly_id :titulo, use: :slugged

  mount_uploader :imagen, ImagenUploader
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  attr_accessible :descripcion, :icono, :nombre

  mount_uploader :icono, IconoUploader

  belongs_to :categoria
end

app/controllers/alianzas_controller.rb
class AlianzasController < InheritedResources::Base
  before_filter :authenticate_admin!, :except => [:index]
  def create
    create! { alianzas_path }
  end

  def update
    update! { alianzas_path }
  end
end

app/controllers/banners_controller.rb
class BannersController < InheritedResources::Base
  before_filter :authenticate_admin!

  def create
    create! { root_path }
  end

  def update
    update! { root_path }
  end

  def destroy
    destroy! { root_path }
  end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    @clientes = Cliente.random
    @banners = Banner.all
  end
end

app/controllers/miembros_controller.rb
class MiembrosController < InheritedResources::Base
  before_filter :authenticate_admin!, :except => [:index, :show]

   def create
    create! { miembros_path }
  end

  def update
    update! { miembros_path }
  end

  def destroy
    destroy! { miembros_path }
  end

end

app/helpers/alianzas_helper.rb
module AlianzasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  # ENCABEZADO
  def encabezado(titulo, imagen, icono, btn)
    "#{'
      <div class="encabezado">
        <div class="container">
          <div class="region">
            <div class="region-title">
              <h2 class="title">' + titulo + '<img src="' + icono + '" /></h2>' +
                if (btn)
                  btn_back
                else
                  ''
                end  + '
            </div>
          </div>
        </div>
        <img src="' + imagen + '" class="title-pic"/>
      </div>'}".html_safe
  end

  def btn_back
    
      '<a href="javascript:history.back(-1)" class="btn-back">< Regresar</a>'.html_safe

  end



  # MENÚ HELPERS
  # list menu maker
  def menu_li(current_page, current_controller, current_url)
    content_tag(:li, :class => lavalamp(current_controller).to_s) do
      link_to_unless_current current_page, current_url do
        content_tag(:span, current_page)
      end
    end
  end

  # extension of menu maker wich applies lavalamp class to the current controller
  def lavalamp(current_controller)
    if params[:controller] == "#{current_controller}"
      'selectedLava' 
    end
  end

  


  # admin controls
  def admin_controls(edit_text, edit_link, direction)
    if current_admin
      "#{'
        <div class="admin-controls">
        <div class="btn-group ' + 
          if (direction === 'up')
            'dropup'
          else
           nil.to_s 
          end  + '">


        <a class="btn btn-edit btn-sm" href="' + edit_link + '">' + edit_text + '</a> 
       

        <div class="btn-group">
          <div class="dropdown">
            <a class="btn btn-default btn-sm" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
               <span class="caret"></span>
            </a>
 
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="' + edit_link + '">' + edit_text + '</a></li>
              <li role="presentation" class="li-delete"></li>
            </ul>

          </div>
        </div>
      </div>
      </div>'}".html_safe
    end
  end

  # admin create
  def admin_create(create_text, create_link)
    if current_admin
      "#{'<div class="admin-control"> 
        <a class="new" href="' + create_link +'">' + create_text + '</a>
      </div>'}".html_safe
    end
  end




 # def paragraph(post, length)
 #   "#{simple_format(truncate(post, :length => length))}"
 # end

  def paragraph(text)
    "#{sanitize(simple_format(text), :tags => %w(p i br b))}".html_safe
  end

  def paragraph_truncate(text, length)
    "#{sanitize(simple_format(truncate(text, :length => length)), :tags => %w(p i br b))}".html_safe
  end





end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper

  def google_maps_api_key
    "AIzaSyBS10UVR-QYWWQilit2l3T-QtarxQERAo4"
  end

  def google_api_url
    "http://maps.googleapis.com/maps/api/js"
  end

  def google_api_access
    "#{google_api_url}?key=#{google_maps_api_key}&libraries=geometry&sensor=false"
  end

  def google_maps_api
    content_tag(:script,:type => "text/javascript",:src => google_api_access) do
    end
  end

end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/miembros_helper.rb
module MiembrosHelper
end

app/helpers/noticias_helper.rb
module NoticiasHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/miembros/_form.html.haml
= form_for @miembro, :html => {:multipart => true} do |f|
  - if @miembro.errors.any?
    #error_explanation
      %h2= "#{pluralize(@miembro.errors.count, "error")} prohibited this miembro from being saved:"
      %ul
        - @miembro.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre
    = f.text_field :nombre
  .field
    = f.label :apellido
    = f.text_field :apellido
  .field
    = f.label :puesto
    = f.text_field :puesto
  .field
    = f.label :foto
    = f.file_field :foto
  .field
    = f.label :descripcion
    = f.text_area :descripcion, class: 'tinymce'
  .field
    = f.label :posicion, 'Posición'
    = f.select :posicion, options_for_select(0..Miembro.all.count)
  .actions
    = f.submit 'Guardar'

app/views/miembros/edit.html.haml
= render 'scripts/tiny_mce'

= encabezado('Editar Miembro del Staff', '/assets/encabezado.jpg', '/assets/icono-editar.png', true)

#region-staff.container
  = render 'form'

app/views/miembros/index.html.haml
= encabezado('Staff', '/assets/encabezado.jpg', '/assets/icono-alianzas.png', false)



#region-staff.container
  = admin_create('Nuevo Miembro', new_miembro_path)
  .region
    .region-title
      %h2.title CONOCE A NUESTRO STAFF DE PROFESIONALES
  - @miembros.each_slice(4) do |miembro|
    .region
      - miembro.each do |miembro|
        .region-inner
          .item-hover-wrapper
            = link_to image_tag(miembro.foto_url(:regular)), miembro
            %h3.title
              = link_to miembro.nombre , miembro
              %br
              = link_to miembro.apellido , miembro
            %h4.subtitle
              = miembro.puesto
            .item-hover
              %i.lupa
              = link_to 'Ver más', miembro, class: 'btn-more'

          = admin_controls('Editar', edit_miembro_path(miembro), 'down')
          - if current_admin
            = link_to 'Eliminar', miembro, :method => :delete, :data => { :confirm => '¿Estás seguro?' }

app/views/miembros/new.html.haml
= render 'scripts/tiny_mce'

= encabezado('Nuevo Miembro del Staff', '/assets/encabezado.jpg', '/assets/icono-nuevo.png', true)

#region-staff.container
  = render 'form'

app/views/miembros/show.html.haml
= encabezado('Staff', '/assets/encabezado.jpg', '/assets/icono-alianzas.png', true)


#region-staff-show.container
  .region
    .region-inner.picture
      = image_tag @miembro.foto_url(:full), class: 'img-responsive'

      %h3.title
        = @miembro.nombre
        %br
        = @miembro.apellido
      %h4.subtitle
        = @miembro.puesto

    .region-inner.description
      = paragraph(raw(@miembro.descripcion))