config/routes.rb
Laboralmedical2013::Application.routes.draw do

  devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  match '/servicios' => 'categorias#servicios', via: :get

  match '/consultorias' => 'categorias#consultorias', via: :get

  scope '/blog' do
    resources :noticias
  end

  resources :categorias do
    resources :servicios
  end

  resources :contactos

  resources :alianzas

  resources :servicios

  scope '/staff' do
    resources :miembros
  end

  resources :clientes

  resources :banners

  root to: 'inicio#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/alianza.rb
class Alianza < ActiveRecord::Base
  attr_accessible :nombre, :logo, :posicion

  default_scope order('posicion ASC')

  mount_uploader :logo, LogoUploader
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  attr_accessible :encabezado, :imagen, :link

  mount_uploader :imagen, SlideUploader
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  attr_accessible :nombre

  has_many :servicios
  TIPOS = ['Servicios','Consultorias']
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :link, :logo

  mount_uploader :logo, IconoUploader

  def self.random
    self.all.sample(4)
  end

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  attr_accessible :email, :mensaje, :nombre, :telefono
end

app/models/miembro.rb
class Miembro < ActiveRecord::Base
  attr_accessible :descripcion, :nombre, :puesto, :foto, :apellido, :posicion

  default_scope order('posicion ASC')

  extend FriendlyId
  friendly_id :nombre, use: :slugged

  mount_uploader :foto, FotoUploader
end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
  attr_accessible :contenido, :imagen, :subtitulo, :titulo

extend FriendlyId
  friendly_id :titulo, use: :slugged

  mount_uploader :imagen, ImagenUploader
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  attr_accessible :descripcion, :icono, :nombre

  mount_uploader :icono, IconoUploader

  belongs_to :categoria
end

app/controllers/alianzas_controller.rb
class AlianzasController < InheritedResources::Base
  before_filter :authenticate_admin!, :except => [:index]
  def create
    create! { alianzas_path }
  end

  def update
    update! { alianzas_path }
  end
end

app/controllers/banners_controller.rb
class BannersController < InheritedResources::Base
  before_filter :authenticate_admin!

  def create
    create! { root_path }
  end

  def update
    update! { root_path }
  end

  def destroy
    destroy! { root_path }
  end
end

app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base
  before_filter :authenticate_admin!
  
  def create
    create! { root_path }
  end

  def update
    update! { root_path }
  end

  def destroy
    destroy! { root_path }
  end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    @clientes = Cliente.random
    @banners = Banner.all
  end
end

app/helpers/alianzas_helper.rb
module AlianzasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  # ENCABEZADO
  def encabezado(titulo, imagen, icono, btn)
    "#{'
      <div class="encabezado">
        <div class="container">
          <div class="region">
            <div class="region-title">
              <h2 class="title">' + titulo + '<img src="' + icono + '" /></h2>' +
                if (btn)
                  btn_back
                else
                  ''
                end  + '
            </div>
          </div>
        </div>
        <img src="' + imagen + '" class="title-pic"/>
      </div>'}".html_safe
  end

  def btn_back
    
      '<a href="javascript:history.back(-1)" class="btn-back">< Regresar</a>'.html_safe

  end



  # MENÚ HELPERS
  # list menu maker
  def menu_li(current_page, current_controller, current_url)
    content_tag(:li, :class => lavalamp(current_controller).to_s) do
      link_to_unless_current current_page, current_url do
        content_tag(:span, current_page)
      end
    end
  end

  # extension of menu maker wich applies lavalamp class to the current controller
  def lavalamp(current_controller)
    if params[:controller] == "#{current_controller}"
      'selectedLava' 
    end
  end

  


  # admin controls
  def admin_controls(edit_text, edit_link, direction)
    if current_admin
      "#{'
        <div class="admin-controls">
        <div class="btn-group ' + 
          if (direction === 'up')
            'dropup'
          else
           nil.to_s 
          end  + '">


        <a class="btn btn-edit btn-sm" href="' + edit_link + '">' + edit_text + '</a> 
       

        <div class="btn-group">
          <div class="dropdown">
            <a class="btn btn-default btn-sm" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
               <span class="caret"></span>
            </a>
 
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="' + edit_link + '">' + edit_text + '</a></li>
              <li role="presentation" class="li-delete"></li>
            </ul>

          </div>
        </div>
      </div>
      </div>'}".html_safe
    end
  end

  # admin create
  def admin_create(create_text, create_link)
    if current_admin
      "#{'<div class="admin-control"> 
        <a class="new" href="' + create_link +'">' + create_text + '</a>
      </div>'}".html_safe
    end
  end




 # def paragraph(post, length)
 #   "#{simple_format(truncate(post, :length => length))}"
 # end

  def paragraph(text)
    "#{sanitize(simple_format(text), :tags => %w(p i br b))}".html_safe
  end

  def paragraph_truncate(text, length)
    "#{sanitize(simple_format(truncate(text, :length => length)), :tags => %w(p i br b))}".html_safe
  end





end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper

  def google_maps_api_key
    "AIzaSyBS10UVR-QYWWQilit2l3T-QtarxQERAo4"
  end

  def google_api_url
    "http://maps.googleapis.com/maps/api/js"
  end

  def google_api_access
    "#{google_api_url}?key=#{google_maps_api_key}&libraries=geometry&sensor=false"
  end

  def google_maps_api
    content_tag(:script,:type => "text/javascript",:src => google_api_access) do
    end
  end

end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/miembros_helper.rb
module MiembrosHelper
end

app/helpers/noticias_helper.rb
module NoticiasHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/alianzas/_form.html.haml
= form_for @alianza, :html => { :multipart => true } do |f|
  - if @alianza.errors.any?
    #error_explanation
      %h2= "#{pluralize(@alianza.errors.count, "error")} prohibited this alianza from being saved:"
      %ul
        - @alianza.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre
    = f.text_field :nombre
  .field
    = f.label :logo
    = f.file_field :logo
  .field
    = f.label :posicion, 'Posición'
    = f.select :posicion, options_for_select(0..Alianza.all.count)
  .actions
    = f.submit 'Guardar'

app/views/alianzas/edit.html.haml
= encabezado('Editar Alianza', '/assets/encabezado.jpg', '/assets/icono-editar.png', true)

#region-alianzas.container
  = render 'form'

app/views/alianzas/index.html.haml
= encabezado('Alianzas', '/assets/encabezado.jpg', '/assets/icono-alianzas.png', false)


.container
  = admin_create('Nueva Alianza', new_alianza_path)

  #alianzas-descripcion.region
    .region-title
      %h2.title ALIANZAS ESTRATEGICAS

    .region-inner
      %p Para mejor nuestros servicios, Laboral Medical posee fuertes alianzas y convenios con prestigiosas empresas e instituciones.

  #alianzas-logos.region
    - @alianzas.each_slice(4) do |alianza|
      .region
        - alianza.each do |alianza|
          .region-inner
            = image_tag alianza.logo_url(:thumb)
            %h3.title= alianza.nombre
            = admin_controls('Editar', edit_alianza_path(alianza), 'down')
            - if current_admin
              = link_to 'Eliminar', alianza, :method => :delete, :data => { :confirm => '¿Estás seguro?' }

app/views/alianzas/new.html.haml
= encabezado('Nueva Alianza', '/assets/encabezado.jpg', '/assets/icono-nuevo.png', true)

#region-alianzas.container
  = render 'form'

app/views/banners/_form.html.haml
= form_for @banner, :html => { :multipart => true } do |f|
  - if @banner.errors.any?
    #error_explanation
      %h2= "#{pluralize(@banner.errors.count, "error")} prohibited this banner from being saved:"
      %ul
        - @banner.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :imagen
    = f.file_field :imagen
  .field
    = f.label :encabezado
    = f.text_field :encabezado
  .field
    = f.label :link
    = f.text_field :link
  .actions
    = f.submit 'Guardar'

app/views/banners/edit.html.haml
= encabezado('Editar Banner', '/assets/encabezado.jpg', '/assets/icono-editar.png', true)

#region-banners.container
  = render 'form'

app/views/banners/new.html.haml
= encabezado('Nuevo Banner', '/assets/encabezado.jpg', '/assets/icono-nuevo.png', true)

#region-banners.container
  = render 'form'

app/views/clientes/_form.html.haml
= form_for @cliente, :html => { :multipart => true } do |f|
  - if @cliente.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cliente.errors.count, "error")} prohibited this cliente from being saved:"
      %ul
        - @cliente.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :logo
    = f.file_field :logo
  .field
    = f.label :link
    = f.text_field :link
  .actions
    = f.submit 'Guardar'

app/views/clientes/edit.html.haml
= encabezado('Editar Cliente', '/assets/encabezado.jpg', '/assets/icono-editar.png', true)

#region-clientes.container
  = render 'form'

app/views/clientes/new.html.haml
= encabezado('Nuevo Cliente', '/assets/encabezado.jpg', '/assets/icono-nuevo.png', true)

#region-clientes.container
  = render 'form'