config/routes.rb
Laboralmedical2013::Application.routes.draw do

  devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

  match '/servicios' => 'categorias#servicios', via: :get

  match '/consultorias' => 'categorias#consultorias', via: :get

  scope '/blog' do
    resources :noticias
  end

  resources :categorias do
    resources :servicios
  end

  resources :contactos

  resources :alianzas

  resources :servicios

  scope '/staff' do
    resources :miembros
  end

  resources :clientes

  resources :banners

  root to: 'inicio#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/alianza.rb
class Alianza < ActiveRecord::Base
  attr_accessible :nombre, :logo, :posicion

  default_scope order('posicion ASC')

  mount_uploader :logo, LogoUploader
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  attr_accessible :encabezado, :imagen, :link

  mount_uploader :imagen, SlideUploader
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  attr_accessible :nombre

  has_many :servicios
  TIPOS = ['Servicios','Consultorias']
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  attr_accessible :link, :logo

  mount_uploader :logo, IconoUploader

  def self.random
    self.all.sample(4)
  end

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  attr_accessible :email, :mensaje, :nombre, :telefono
end

app/models/miembro.rb
class Miembro < ActiveRecord::Base
  attr_accessible :descripcion, :nombre, :puesto, :foto, :apellido, :posicion

  default_scope order('posicion ASC')

  extend FriendlyId
  friendly_id :nombre, use: :slugged

  mount_uploader :foto, FotoUploader
end

app/models/noticia.rb
class Noticia < ActiveRecord::Base
  attr_accessible :contenido, :imagen, :subtitulo, :titulo

extend FriendlyId
  friendly_id :titulo, use: :slugged

  mount_uploader :imagen, ImagenUploader
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
  attr_accessible :descripcion, :icono, :nombre

  mount_uploader :icono, IconoUploader

  belongs_to :categoria
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    @clientes = Cliente.random
    @banners = Banner.all
  end
end

app/helpers/alianzas_helper.rb
module AlianzasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


  # ENCABEZADO
  def encabezado(titulo, imagen, icono, btn)
    "#{'
      <div class="encabezado">
        <div class="container">
          <div class="region">
            <div class="region-title">
              <h2 class="title">' + titulo + '<img src="' + icono + '" /></h2>' +
                if (btn)
                  btn_back
                else
                  ''
                end  + '
            </div>
          </div>
        </div>
        <img src="' + imagen + '" class="title-pic"/>
      </div>'}".html_safe
  end

  def btn_back
    
      '<a href="javascript:history.back(-1)" class="btn-back">< Regresar</a>'.html_safe

  end



  # MENÚ HELPERS
  # list menu maker
  def menu_li(current_page, current_controller, current_url)
    content_tag(:li, :class => lavalamp(current_controller).to_s) do
      link_to_unless_current current_page, current_url do
        content_tag(:span, current_page)
      end
    end
  end

  # extension of menu maker wich applies lavalamp class to the current controller
  def lavalamp(current_controller)
    if params[:controller] == "#{current_controller}"
      'selectedLava' 
    end
  end

  


  # admin controls
  def admin_controls(edit_text, edit_link, direction)
    if current_admin
      "#{'
        <div class="admin-controls">
        <div class="btn-group ' + 
          if (direction === 'up')
            'dropup'
          else
           nil.to_s 
          end  + '">


        <a class="btn btn-edit btn-sm" href="' + edit_link + '">' + edit_text + '</a> 
       

        <div class="btn-group">
          <div class="dropdown">
            <a class="btn btn-default btn-sm" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
               <span class="caret"></span>
            </a>
 
            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
              <li role="presentation"><a role="menuitem" tabindex="-1" href="' + edit_link + '">' + edit_text + '</a></li>
              <li role="presentation" class="li-delete"></li>
            </ul>

          </div>
        </div>
      </div>
      </div>'}".html_safe
    end
  end

  # admin create
  def admin_create(create_text, create_link)
    if current_admin
      "#{'<div class="admin-control"> 
        <a class="new" href="' + create_link +'">' + create_text + '</a>
      </div>'}".html_safe
    end
  end




 # def paragraph(post, length)
 #   "#{simple_format(truncate(post, :length => length))}"
 # end

  def paragraph(text)
    "#{sanitize(simple_format(text), :tags => %w(p i br b))}".html_safe
  end

  def paragraph_truncate(text, length)
    "#{sanitize(simple_format(truncate(text, :length => length)), :tags => %w(p i br b))}".html_safe
  end





end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper

  def google_maps_api_key
    "AIzaSyBS10UVR-QYWWQilit2l3T-QtarxQERAo4"
  end

  def google_api_url
    "http://maps.googleapis.com/maps/api/js"
  end

  def google_api_access
    "#{google_api_url}?key=#{google_maps_api_key}&libraries=geometry&sensor=false"
  end

  def google_maps_api
    content_tag(:script,:type => "text/javascript",:src => google_api_access) do
    end
  end

end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/miembros_helper.rb
module MiembrosHelper
end

app/helpers/noticias_helper.rb
module NoticiasHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/layouts/_html.html.haml
!!!
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7 ie6">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8 ie7">
/[if IE 8] <html class="no-js lt-ie9 ie8">
/ [if gt IE 8]><!
%html.no-js
  / <![endif]
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    %title= content_for?(:title) ? yield(:title) : "Laboral Medical | Salud Ocupacional"
    %meta(name="description" content="Somos una organización especializada que brinda servicios enfocados en temas de salud ocupacional, capacitaciones, selección de personal dirigida al profesional, organizaciones y público en general buscando que nuestros cliente")
    %meta(name="keywords" content="Chequeos médicos ocupacionales, Implementación de sistemas de gestión, capacitaciones.")
    %meta(name="robot" content="index,follow")
    %meta(name="copyright" content="Todos los derechos reservados &copy; Laboral Medical.")
    %meta(name="author" content="Kosmyka.com")
    %meta(name="language" content="Spanish")
    %meta(name="revisit-after" content="1")
    %meta(name="googlebot" content="index,follow")
    %meta(name="city" content="Lima")
    %meta(name="country" content="Peru")
    %meta(name="state" content="Lima")
    %meta(name="zip code" content="Lima 18")
    %meta(name="subject" content="Laboral Medical")
    %meta(name="geo.position" content="-9;-75")
    %meta(name="geo.country" content="PE")
    %meta(name="geo.region" content="PE-LIM")
    %meta(name="geo.placename" content="Miraflores")
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag 'application'
    = yield :javascript
    = favicon_link_tag '/ico/laboralmedical-icon-144.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag '/ico/laboralmedical-icon-114.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag '/ico/laboralmedical-icon-72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag '/ico/laboralmedical-icon-57.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag '/ico/favicon.ico', :rel => 'shortcut icon'

    = yield(:head)

app/views/layouts/_nav_advanced.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  = render 'shared/social_small'
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar

  / Collect the nav links, forms, and other content for toggling
  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav.navbar-right
      = menu_li('Inicio', 'inicio', root_path)
      = menu_li('Servicios', 'categorias', servicios_path)
      = menu_li('Consultorías', 'categorias', consultorias_path)
      = menu_li('Blog', 'noticias', noticias_path)
      = menu_li('Staff', 'miembros', miembros_path)
      = menu_li('Alianzas', 'alianzas', alianzas_path)
      - if current_admin
        = menu_li('Contacto', 'contactos', contactos_path)
      - else
        = menu_li('Contacto', 'contactos', new_contacto_path)

      - if current_admin
        %li
          = link_to 'Cerrar Sesión', destroy_admin_session_path, :method => :delete
      
  / /.navbar-collapse

app/views/layouts/application.html.haml
= render 'layouts/html'

%body{id: bodyid, class: bodyclass}
  %header#main-header
    .container
      .region
        .region-inner
          %h1#logo
            = link_to image_tag('logo.png', title: 'Laboral Medical', alt: 'Laboral Medical'), root_path, class: 'navbar-brand'
          = render 'layouts/nav_advanced'


  #content
    = yield

  %footer#main-footer
    .container
      .region
        .region-title
          %h2.element-invisible Footer
        .region-inner
          = render 'shared/social_large'
          %p.copyright
            LABORAL MEDICAL TODOS LOS DERECHOS RESERVADOS 2013.
  = render '/shared/google_analytics'

app/views/scripts/_tiny_mce.html.haml
- content_for :javascript do
  = javascript_include_tag 'tinymce.js'
  :javascript
    $(document).ready(function() {
      tinymce.init({
        selector: "textarea",
        theme: "advanced",
        forced_root_block : false,
        force_br_newlines : true,
        force_p_newlines : false,
        theme_advanced_toolbar_location: "top",
        theme_advanced_toolbar_align: "left",
        theme_advanced_statusbar_location: "bottom",
        theme_advanced_buttons1: "bold, italic, underline",
        theme_advanced_buttons2: "",
        theme_advanced_buttons3: "",
        plugins: "preview, autolink",
        });
    });

app/views/shared/_google_analytics.html.erb
<script type="text/javascript" charset="utf-8">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28243416-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/shared/_mapa.html.erb
<div style='width: 100%;'>
  <div id="map_canvas" style='width: 100%; height: 500px;'></div>
</div>

app/views/shared/_siguenos_facebook.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=231889076968885";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

<section id="siguenos-facebook" class="container region-centered">
  <div class="region">
    <div class="region-inner">
       <h2 class="title">
         Síguenos en Facebook
       </h2>
         <div class="fb-like-box" data-href="https://www.facebook.com/laboralmedicalperu" data-width="940" data-height="260" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="false"></div>
    </div>
  </div>
</section>

app/views/shared/_social_large.html.haml
%ul.social-links.clearfix
  %li
    = link_to content_tag(:i, '', class: 'icon mail'), 'mailto:info@laboralmedicalperu.com'
    = mail_to 'info@laboralmedicalperu.com', 'info@laboralmedicalperu.com', target: '_blank'
  %li
    = link_to content_tag(:i, '', class: 'icon location'), new_contacto_path
    %p Grimaldo del Solar #231<br />Of. 101, Miraflores, Lima.
  %li
    = link_to content_tag(:i, '', class: 'icon facebook'), 'https://www.facebook.com/laboralmedicalperu', target: '_blank'
    = link_to 'fb.com/laboralmedicalperu', '', target: '_blank'
  %li
    = link_to content_tag(:i, '', class: 'icon telefono'), new_contacto_path
    %p 2495257 / 4455059 <br />999857980 / 413*1130

app/views/shared/_social_small.html.haml
%ul.social-links.clearfix
  %li
    = link_to content_tag(:i, '', class: 'icon mail_small'), 'mailto:info@laboralmedicalperu.com'
  %li
    = link_to content_tag(:i, '', class: 'icon location_small'), new_contacto_path
  %li
    = link_to content_tag(:i, '', class: 'icon facebook_small'), 'http://www.facebook.com/laboralmedicalperu', target: '_blank'
  %li
    = link_to content_tag(:i, '', class: 'icon telefono_small'), new_contacto_path